### ISSUE TITLE
Unsatisfied version of OpenCL found for versions earlier than 2.1

### ISSUE THREAD

**Issue by stratika** [beehive-lab/TornadoVM#186]
### Describe the bug 
The current version of TornadoVM requires OpenCL 2.1 version to be installed since it utilizes in the native layer the `clCreateProgramWithIL` function. This function has been added since this [commit](https://github.com/beehive-lab/TornadoVM/commit/1bf7981c44dfb84050e703a4ef9f6d4b2ff415ea) and it is used to pass SPIR-V binaries and execute them through OpenCL.

However, if TornadoVM is built without OpenCL 2.1 and it is configured to be built with only the OpenCL backend, this function is not used but it is looked if is exist in the shared library of OpenCL (libOpenCL.so). 

And since it is mising, it throws the following error:
```bash
$ tornado --devices
.lang.UnsatisfiedLinkError: version `OPENCL_2.1' not found (required by /home/thanos/repositories/TornadoVM/dist/tornado-sdk/tornado-sdk-0.14-dev-700f839/lib/libtornado-opencl.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at tornado.drivers.opencl@0.14-dev/uk.ac.manchester.tornado.drivers.opencl.OpenCL.<clinit>(OpenCL.java:69)
        at tornado.drivers.opencl@0.14-dev/uk.ac.manchester.tornado.drivers.opencl.OCLDriver.<init>(OCLDriver.java:56)
        at tornado.drivers.opencl@0.14-dev/uk.ac.manchester.tornado.drivers.opencl.OCLTornadoDriverProvider.createDriver(OCLTornadoDriverProvider.java:50)
        at tornado.runtime@0.14-dev/uk.ac.manchester.tornado.runtime.TornadoCoreRuntime.loadDrivers(TornadoCoreRuntime.java:173)
        at tornado.runtime@0.14-dev/uk.ac.manchester.tornado.runtime.TornadoCoreRuntime.<init>(TornadoCoreRuntime.java:107)
        at tornado.runtime@0.14-dev/uk.ac.manchester.tornado.runtime.TornadoCoreRuntime.<clinit>(TornadoCoreRuntime.java:83)
        at tornado.drivers.common@0.14-dev/uk.ac.manchester.tornado.drivers.TornadoDeviceQuery.main(TornadoDeviceQuery.java:73)
```

### How To Reproduce

You will need a machine that has not installed OpenCL 2.1 and you can run:

```bash
$ tornado --devices
```

### Expected behavior 

To be functional with OpenCL 1.2 when OpenCL is selected as a backend, and to receive a warning regarding the missing compatible version if SPIR-V is going to be configured for building.

### Computing system setup (please complete the following information):
 - OS: Centos 7
 - OpenCL Version: 1.2 
 - PTX Version (if applicable)
 - Level Zero & SPIRV Versions (if applicable)
 - TornadoVM commit id: 700f839

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
I took a look at this. So we import all Khronos OpenCL headers to facilitate the installation of the OpenCL backend. In these headers, we use OpenCL 3.0. The issue is that, as soon as the `clCreateProgramWithIL`, we need to load the `so` dynamic library with this function in it. 

Since NVIDIA and Intel support OpenCL 3.0, I suggest that TornadoVM requires at least OpenCL 2.1. For the FPGA builds, we can have a custom-built to avoid this call (all major OpenCL implementations for OpenCL are based on OpenCL 1.0, still).
