### ISSUE TITLE
long as parameter causes a ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by IIlllII** [beehive-lab/TornadoVM#228]
### Describe the bug 
On my M1 using graal 17 an ArrayIndexOutOfBoundsException is thrown when using a long as a parameter. It works if the long is in an array, and an int also works instead of the long.

From digging around in the debugger the failure seems to be caused the by Long.longValue() method being parsed for accesses instead of the 'test' method, which means the amount of access arguments is wrong.

Stacktrace is:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at tornado.runtime@0.15/uk.ac.manchester.tornado.runtime.graph.TornadoGraphBuilder.buildGraph(TornadoGraphBuilder.java:131)
	at tornado.runtime@0.15/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.compile(TornadoTaskGraph.java:628)
	at tornado.runtime@0.15/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.compileToTornadoVMBytecode(TornadoTaskGraph.java:697)
	at tornado.runtime@0.15/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.scheduleInner(TornadoTaskGraph.java:793)
	at tornado.runtime@0.15/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.schedule(TornadoTaskGraph.java:1203)
	at tornado.api@0.15/uk.ac.manchester.tornado.api.TaskGraph.execute(TaskGraph.java:782)
	at tornado.api@0.15/uk.ac.manchester.tornado.api.ImmutableTaskGraph.execute(ImmutableTaskGraph.java:73)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at tornado.api@0.15/uk.ac.manchester.tornado.api.TornadoExecutionPlan$TornadoExecutor.execute(TornadoExecutionPlan.java:297)
	at tornado.api@0.15/uk.ac.manchester.tornado.api.TornadoExecutionPlan.execute(TornadoExecutionPlan.java:126)
	at games.Repro.main(Repro.java:47)
```

### How To Reproduce

```

public class Repro {

    public static void test(
                            int size,
                            final long[] seeds,
                            //final long[] enh, //This works
                            long enh, //This fails
                            final int[] result1) {

        for (@Parallel int i = 0; i < size; i++) {
            //long seed = seeds[i%seeds.length] + enh[0];
            long seed = seeds[i%seeds.length] + enh;
            result1[i] = (int)seed%Integer.MAX_VALUE;
        }
    }

    public static void main(String[] args) {

        int[] r1 = new int[1];

        long[] seeds = new long[] {3};

        //long[] enh = new long[] {10};
        long enh = 10L;

        int size = 1;

        TaskGraph s0 = new TaskGraph("s0")
                .transferToDevice(DataTransferMode.FIRST_EXECUTION,size,seeds,enh)
                .task("t0", Repro::test,
                        size,
                        seeds,
                        enh,
                        r1)
                .transferToHost(DataTransferMode.EVERY_EXECUTION,r1);

        ImmutableTaskGraph immutableTaskGraph = s0.snapshot();
        TornadoExecutionPlan executorPlan = new TornadoExecutionPlan(immutableTaskGraph);
        executorPlan.execute();

        System.out.println("Res: "+r1[0]);
    }

}

```
### Expected behavior 

Expectation was that the program should work (output "Res: 13"), or a more descriptive error if a long can not be used like this.

### Computing system setup (please complete the following information):
 - OS: macOs Ventura 13.1, M1 mac (FVFGK4B9Q05N)
 - OpenCL C 1.2, 
 - TornadoVM commit id: 0.15 tag 94f2fca

### Additional context

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
Thank you for the report. This is a bug. Tornado should be able to compile and run this code. We will look into it.

**Comment by stratika** [comment]
I am working on this issue, we will patch a fix soon.

**Comment by stratika** [comment]
A patch is implemented and a PR is created in the internal repository so that to test it on our Jenkins CI pipeline. The PR is under review. We will update soon.

**Comment by stratika** [comment]
The patch has been merged in the `develop` and `master` branches. I will close this issue. @IIlllII please try it, and feel free to re-open it if your example is still failing in your system.
