### ISSUE TITLE
Support GraalVM 21.0.2 

### ISSUE THREAD

**Issue by jjfumero** [beehive-lab/TornadoVM#336]
GraalVM JIT Compiler 21.0.2 changes the compiler interface for some of the IR nodes:

This feature should update the compiler with the latest version. 

```bash
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project tornado-drivers-common: Compilation failure: Compilation failure:

[ERROR] C:\dev\TornadoVM\tornado-drivers\drivers-common\src\main\java\uk\ac\manchester\tornado\drivers\common\compiler\phases\guards\ExceptionSuppression.java:[63,22] error: cannot find symbol
[ERROR] symbol: method getAnchoredNode()
[ERROR] location: variable anchor of type ValueAnchorNode
[ERROR] C:\dev\TornadoVM\tornado-drivers\drivers-common\src\main\java\uk\ac\manchester\tornado\drivers\common\compiler\phases\guards\ExceptionSuppression.java:[66,22] error: cannot find symbol
[ERROR] symbol: method removeAnchoredNode()
[ERROR] location: variable anchor of type ValueAnchorNode
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :tornado-drivers-common
Error running 'mvn clean': Command '['mvn', '-T1.5C', '-Dcmake.root.dir=$CMAKE_ROOT', '-Pgraal-jdk-21,ptx-backend,opencl-backend', 'install']' returned non-zero exit status 1.
Traceback (most recent call last):
File "/c/dev/TornadoVM/bin/compile", line 373, in
main()
File "/c/dev/TornadoVM/bin/compile", line 365, in main
mvn_build_result = build_tornadovm(args, backend_profiles)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/c/dev/TornadoVM/bin/compile", line 264, in build_tornadovm
return result
^^^^^^
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
make: *** [Makefile:15: graal-jdk-21] Error 1
```

**Comment by mikepapadim** [comment]
There are some changes with the GraalVM-21.0.2: https://github.com/beehive-lab/TornadoVM/pull/337 
The above-mentioned PR solves the issue if you want to use GraalVM-21.0.2.

**Comment by Blacktoviche** [comment]
I'm using Oracle GraalVM 21.0.9+7.1 (build 21.0.9+7-LTS-jvmci-23.1-b79)
Got the same issue.
Do I have to upgrade to JDK 25? or openJDK 21 ?

**Comment by mikepapadim** [comment]
Great! just mark the answer solution! thanks
