### ISSUE TITLE
Installation script using `--javaHome` fails

### ISSUE THREAD

**Issue by spamegg1** [beehive-lab/TornadoVM#391]
### Describe the bug 
Using SDKMAN to manage JDKs, following the advice given in `--listJDKs`

```bash
If you want to select another version of OpenJDK, you can use --javaHome <pathToJavaHome> and install as follows:
      $ ./bin/tornadovm-installer --backend <BACKEND> --javaHome <pathToJavaHome>
```
installation fails to start, with a `TypeError`.

### How To Reproduce

```bash
$ git clone https://github.com/beehive-lab/TornadoVM/
$ cd TornadoVM
$ ./bin/tornadovm-installer --backend opencl --javaHome /home/spam/.sdkman/candidates/java/current/                 
Traceback (most recent call last):
  File "/home/spam/Public/TornadoVM/./bin/tornadovm-installer", line 436, in <module>
    installer.install(args)
  File "/home/spam/Public/TornadoVM/./bin/tornadovm-installer", line 318, in install
    if (args.javaHome != None and "graal" in args.javaHome) or ("graal" in args.jdk):
TypeError: argument of type 'NoneType' is not iterable
```

### Expected behavior 

Installation should work fine.

### Computing system setup (please complete the following information):
 - OS: Ubuntu 22.04 LTS
 - OpenCL and Driver versions: OpenCL 1.1 Mesa 23.2.1-1ubuntu3.1~22.04.2
```

### Additional context

Add any other context about the problem here.

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
Thank you for the report. I can reproduce it. 

In the mean while, while we fix this, you can try the following:

```bash
./bin/tornadovm-installer --backend opencl --jdk jdk21
```

**Comment by jjfumero** [comment]
You can apply also this path. I will open a PR in a bit:

```diff
git diff
diff --git a/bin/tornadovm-installer b/bin/tornadovm-installer
index 4e16bdad2..e27677590 100755
--- a/bin/tornadovm-installer
+++ b/bin/tornadovm-installer
@@ -315,7 +315,7 @@ class TornadoInstaller:
 
         makeJDK = "jdk21"
         polyglotOption = ""
-        if (args.javaHome != None and "graal" in args.javaHome) or ("graal" in args.jdk):
+        if (args.javaHome != None and "graal" in args.javaHome) or (args.jdk != None and "graal" in args.jdk):
             makeJDK = "graal-jdk-21"
             polyglotOption = self.composePolyglotOption(args)
```

**Comment by stratika** [comment]
The PR with the fix is now merged. Please pull master or develop and try it. If you have any further issue, feel free to reopen the issue. I will close it.
