### ISSUE TITLE
Bitset benchmarks failing - MBP 16 MacOS 10.15.3, TornadoVM SDK 0.6, GraalVM Java 8 19.3.0

### ISSUE THREAD

**Issue by hyiger** [beehive-lab/TornadoVM#5]
```bash
tornado --devices                                                

Number of Tornado drivers: 1
Total number of devices  : 3
Tornado device=0:0
	Apple -- Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
		Global Memory Size: 32.0 GB
		Local Memory Size: 32.0 KB
		Workgroup Dimensions: 3
		Max WorkGroup Configuration: [1024, 1, 1]
		Device OpenCL C version: OpenCL C 1.2

Tornado device=0:1
	Apple -- Intel(R) UHD Graphics 630
		Global Memory Size: 1.5 GB
		Local Memory Size: 64.0 KB
		Workgroup Dimensions: 3
		Max WorkGroup Configuration: [256, 256, 256]
		Device OpenCL C version: OpenCL C 1.2

Tornado device=0:2
	Apple -- AMD Radeon Pro 5500M Compute Engine
		Global Memory Size: 8.0 GB
		Local Memory Size: 64.0 KB
		Workgroup Dimensions: 3
		Max WorkGroup Configuration: [256, 256, 256]
		Device OpenCL C version: OpenCL C 1.2
```

Environment vars:
```bash
TORNADO_SDK=/usr/local/tornado-sdk/tornado-sdk-0.6-c0b3304
JAVA_HOME=/usr/local/graalvm-ce-java8/19.3.0/Contents/Home
DEVICES=0:0,0:1,0:2
```

```bash
tornado-benchmarks.py
```

Stack trace:
```
bm=bitset-131-8192, id=java-reference      , average=1.871792e+03, median=1.492000e+03, firstIteration=5.065290e+05, best=1.128000e+03
uk.ac.manchester.tornado.drivers.opencl> notify error:
uk.ac.manchester.tornado.drivers.opencl> [CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: build program driver returned (-2)
uk.ac.manchester.tornado.drivers.opencl> notify error:
uk.ac.manchester.tornado.drivers.opencl> OpenCL Warning : clBuildProgram failed: could not build program for 0xffffffff (Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz) (err:-2)
uk.ac.manchester.tornado.drivers.opencl> notify error:
uk.ac.manchester.tornado.drivers.opencl> [CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
<program source>:33:3: error: expected expression
  else
  ^


Exception in thread "main" uk.ac.manchester.tornado.api.exceptions.TornadoRuntimeException: [ERROR] Generated Kernel is NULL. 
Please report this issue to https://github.com/beehive-lab/TornadoVM
	at uk.ac.manchester.tornado.drivers.opencl.graal.OCLInstalledCode.checkKernelNotNull(OCLInstalledCode.java:353)
	at uk.ac.manchester.tornado.drivers.opencl.graal.OCLInstalledCode.submitWithoutEvents(OCLInstalledCode.java:359)
	at uk.ac.manchester.tornado.drivers.opencl.graal.OCLInstalledCode.launchWithoutDeps(OCLInstalledCode.java:389)
	at uk.ac.manchester.tornado.runtime.TornadoVM.execute(TornadoVM.java:498)
	at uk.ac.manchester.tornado.runtime.TornadoVM.execute(TornadoVM.java:194)
	at uk.ac.manchester.tornado.runtime.tasks.TornadoTaskSchedule.scheduleInner(TornadoTaskSchedule.java:421)
	at uk.ac.manchester.tornado.runtime.tasks.TornadoTaskSchedule.schedule(TornadoTaskSchedule.java:642)
	at uk.ac.manchester.tornado.api.TaskSchedule.execute(TaskSchedule.java:230)
	at uk.ac.manchester.tornado.benchmarks.bitset.BitsetTornado.code(BitsetTornado.java:71)
	at uk.ac.manchester.tornado.benchmarks.BenchmarkDriver.benchmark(BenchmarkDriver.java:96)
	at uk.ac.manchester.tornado.benchmarks.BenchmarkRunner.benchmarkAll(BenchmarkRunner.java:113)
	at uk.ac.manchester.tornado.benchmarks.BenchmarkRunner.run(BenchmarkRunner.java:82)
	at uk.ac.manchester.tornado.benchmarks.BenchmarkRunner.main(BenchmarkRunner.java:154)
```

**Comment by hyiger** [comment]
All the bitset benchmarks fail, all others successful.

**Comment by jjfumero** [comment]
Thank you @hyiger for reporting this. We just pushed a fix.
