### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "object" is null

### ISSUE THREAD

**Issue by silvercall** [beehive-lab/TornadoVM#554]
### Describe the bug 
I can not start tornadovm because of NullPointerException
Here is the debug log:
INFO: interpreter for device  [NVIDIA CUDA] -- NVIDIA GeForce GTX 1660 SUPER is ready to go
Sep 09, 2024 9:44:42 PM uk.ac.manchester.tornado.runtime.common.TornadoLogger trace
INFO: cannot wrap field: array type=[Ljava.util.concurrent.ConcurrentHashMap$Node;
Sep 09, 2024 9:44:42 PM uk.ac.manchester.tornado.runtime.common.TornadoLogger trace
INFO: cannot wrap field: array type=[Ljava.util.concurrent.ConcurrentHashMap$Node;
Sep 09, 2024 9:44:42 PM uk.ac.manchester.tornado.runtime.common.TornadoLogger trace
INFO: cannot wrap field: array type=[Ljava.util.concurrent.ConcurrentHashMap$CounterCell;

java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "object" is null
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.mm.OCLXPUBuffer.<init>(OCLXPUBuffer.java:76)
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.mm.OCLXPUBuffer.<init>(OCLXPUBuffer.java:151)
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.mm.OCLXPUBuffer.<init>(OCLXPUBuffer.java:151)
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.mm.OCLXPUBuffer.<init>(OCLXPUBuffer.java:151)
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.mm.OCLXPUBuffer.<init>(OCLXPUBuffer.java:151)
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.mm.OCLXPUBuffer.<init>(OCLXPUBuffer.java:151)
	at tornado.drivers.opencl@1.0.8-dev/uk.ac.manchester.tornado.drivers.opencl.runtime.OCLTornadoDevice.createDeviceBuffer(OCLTornadoDevice.java:556)

I have added following jvm options:
--add-opens
java.base/java.util.concurrent=tornado.drivers.opencl,tornado.runtime

But still tornadovm can not run the program

### Computing system setup (please complete the following information):
 - OS: [Ubuntu 22.04]
 - OpenCL and Driver versions: OpenCL 3.0

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
Hi @silvercall . Can you please expand about the issue? We do have a template for issues like this:
- Description
- Testcase
- Platform used, drivers and TornadoVM backend used.
